name: Triggered Workflow
on:
  workflow_dispatch:
    inputs:
      custom_message:
        description: 'Custom message from sanweb'
        required: false
        default: 'Triggered from sanweb'
jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Received: ${{ github.event.inputs.custom_message }}"
